### ISSUE TITLE
AttributeError: 'Mobileclient' object has no attribute 'search_all_access'

### ISSUE THREAD

**Issue by mzramna** [iXce/gmusicimport#12]
it gives this issue when i run
Traceback (most recent call last):
  File "/home/USER/desktop/gmusicimport.py", line 52, in <module>
    results = client.search_all_access(query)
AttributeError: 'Mobileclient' object has no attribute 'search_all_access'

btw it have a ")" more in the line 38 that was easily fixed but an issue is a issue

**Comment by clidx** [comment]
Can confirm both bugs. I checked the gmusicapi docs and there is no search_all_access. Maybe it changed, but it's just "search".

But once I change that, I get another error

`Logging in as "x" to Google Play Music
Password: 
Importing Jams
Traceback (most recent call last):
  File "gmusicimport.py", line 64, in <module>
    if hit["score"] > 50:
KeyError: 'score'
`
